config/routes.rb
Rainstorming::Application.routes.draw do
 
 resources :users 

 
 
 root to: 'pages#home'

 match '/home',  to: 'pages#home'   

  match '/registrati',  to: 'users#new' 
  match '/login',       to: 'sessions#new'
  match '/signout',     to: 'sessions#destroy', via: :delete
  match '/settings',    to: '@users#edit', via: :edit
  
  match '/progetti', to: 'pages#progetti'  
  match '/designers', to: 'users#index'  
  match '/annunci', to: 'sessions#annunci'
  
  
  match '/missioni', to: 'pages#missioni'  
  match '/contatti', to: 'pages#contatti'  
  match '/termini', to: 'pages#termini'  
  match '/privacy', to: 'pages#privacy'
  match '/sudinoi', to: 'pages#sudinoi'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def sudinoi
  end

  def contatti
  end

  def termini
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
   def full_title(page_title)
   base_title = "Rainstorming Design"
   if page_title.empty?
   base_title
   else
   "#{base_title} | #{page_title}"
   end
 end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<!-------------------------------------------------! inizio footer -->
    <footer>
<!------------------------------! inizio riga1 del footer -->
    	<div id="f_riga1"><div class="s_1260">
        
        	<div id="logo_f"></div>
            <p>Una rete per realizzare la tua pioggia d'idee!</p>
        
        </div></div>
<!------------------------------! fine riga1 del footer -->
<!------------------------------! inizio riga2 del footer -->
        <div id="f_riga2"><div class="s_1260">
        
        	<nav>
            	<ul id="menu1_f">
                
                	<li><a href="#">Su di noi</a></li>
                	<li><a href="#">Missione</a></li>
                	<li><a href="#">Contatti</a></li>
                    <li><a href="#">Termini</a></li>
                	<li><a href="#">Privacy</a></li>

                </ul>
            </nav>
            
            <nav>
               	<ul id="menu2_f">

                	<li style="display:block; float:left; margin-top:19px">Seguici anche su: &nbsp;</li>
                	<li><%= link_to image_tag("rainstorming_design_icona_twitter.png", alt: "Icona rainstorming design twitter", height: "35", width:"35"), '#', title: "Segui Rainstorming Design su Twitter" %></li>
                	<li><%= link_to image_tag("rainstorming_design_icona_facebook.png", alt: "Icona rainstorming design facebook", height: "35", width:"35"), '#', title: "Segui Rainstorming Design su Facebook" %></li>
					<li><%= link_to image_tag("rainstorming_design_icona_vimeo.png", alt: "Icona rainstorming design vimeo", height: "35", width:"35"), '#', title: "Segui Rainstorming Design su Vimeo" %></li>                	
					<li><%= link_to image_tag("rainstorming_design_icona_linkedin.png", alt: "Icona rainstorming design linkedin", height: "35", width:"35"), '#', title: "Segui Rainstorming Design su Linkedin" %></li>               	
                    
                </ul>
            </nav>
        
        </div></div>
<!------------------------------! fine riga2 del footer -->
<!------------------------------! inizio riga3 del footer -->
    	<div id="f_riga3"><div class="s_1260">
        
            <nav>
               	<ul class="mappa_footer">
					<li>Progettisti</li>
                	<li><a href="#">I più votati del mese</a></li>
                	<li><a href="#">Webdesign</a></li>
                	<li><a href="#">Grafica 2D</a></li>
                	<li><a href="#">Grafica 3D</a></li>
                	<li><a href="#">Industrial design</a></li>
                	<li><a href="#">Transportation design</a></li>
                	<li><a href="#">Ecodesign</a></li>
                	<li><a href="#">Fashion design</a></li>
                	<li><a href="#">Interior/Exterior</a></li>
                </ul>
            </nav>
            
            <nav>
               	<ul class="mappa_footer">
					<li>Progetti</li>
                	<li><a href="#">La pioggia del mese</a></li>
                	<li><a href="#">Webdesign</a></li>
                	<li><a href="#">Grafica 2D</a></li>
                	<li><a href="#">Grafica 3D</a></li>
                	<li><a href="#">Industrial design</a></li>
                	<li><a href="#">Transportation design</a></li>
                	<li><a href="#">Ecodesign</a></li>
                	<li><a href="#">Fashion design</a></li>
                	<li><a href="#">Interior/Exterior</a></li>
                </ul>
            </nav>

            <nav>
               	<ul class="mappa_footer">
					<li>Annunci</li>
                	<li><a href="#">I più recenti</a></li>
                	<li><a href="#">Webdesign</a></li>
                	<li><a href="#">Grafica 2D</a></li>
                	<li><a href="#">Grafica 3D</a></li>
                	<li><a href="#">Industrial design</a></li>
                	<li><a href="#">Transportation design</a></li>
                	<li><a href="#">Ecodesign</a></li>
                	<li><a href="#">Fashion design</a></li>
                	<li><a href="#">Interior/Exterior</a></li>
                </ul>
            </nav>
        
        	<div id="marchi"></div>
        
        </div></div>
<!------------------------------! fine riga3 del footer -->
<!------------------------------! inizio riga4 del footer -->
    	<div id="f_riga4">
        
        	<a rel="license" href="http://creativecommons.org/licenses/by-nd/3.0/it/"><img alt="Licenza Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-nd/3.0/it/88x31.png" height="18" width="50" /></a> &nbsp; Rainstorming è distribuito con <a rel="license" href="http://creativecommons.org/licenses/by-nd/3.0/it/" style="vertical-align:top;">licenza Creative Commons Attribuzione - Non opere derivate 3.0 Italia</a>. Tutti i materiali degli utenti sono protetti da copyright. 
        
        </div>
<!------------------------------! fine riga4 del footer -->
    </footer>
<!----------------------------------------------------! fine footer -->
 
 
 
 
  
  <!--[if lt IE 7 ]>
    <script src="js/libs/dd_belatedpng.js"></script>
    <script>DD_belatedPNG.fix('img, .png_bg'); // aggiusta qualsiasi tag <img> o qualsiasi proprietà background-image di .png_bg. Anche per favore leggi goo.gl/mZiyb </script>
  <![endif]-->

app/views/layouts/_header.html.erb
<!--------------------------------------------------! inizio header -->
    <header id="header"><div class="s_1260">
<!------------------------------! inizio prima parte -->
    	<%= link_to "", root_path, id: "logo" %>
        <nav>
			<ul id="menu1">
            
            	<li><%= link_to "Home", root_path, title: "Pagina iniziale di Rainstorming Design" %></li>
            	<li><%= link_to "Designers", users_path, title: "I creative di Rainstorming Design" %></li>
            	<li><%= link_to "Progetti", progetti_path, title: "Progetti su Rainstorming Design" %></li>
            	<li><%= link_to "Annunci", annunci_path, title: "Annunci Rainstorming Design" %></li>
            	
     
            	             
            </ul>
        </nav>
<!------------------------------! fine prima parte -->
<div class="clear"></div>

    </div></header>
<!---------------------------------------------------! fine header --><div class="clear"></div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--> 

    <script type="text/javascript" src="jquery.inputfocus-0.9.min.js"></script>
    <script type="text/javascript" src="jquery.main.js"></script>

   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js" type="text/javascript"></script>
   <script src="jquery.tabSlideOut.v1.3.js"></script>
         

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title><%= full_title(yield(:title)) %></title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <%= render 'layouts/shim' %>
  
  
 </head>
 
   <body>

  <%= render 'layouts/header' %>
  
  <div class="container">
   
   <% flash.each do |key, value| %>
   
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
   
      
   <% end %>
   
   <%= yield %>
   
   
   <%= render 'layouts/footer' %>
   <%= debug(params) if Rails.env.development? %>
   
  

  </body>  
</html>

app/views/pages/contatti.html.erb
<h1>Pages#contatti</h1>
<p>Find me in app/views/pages/contatti.html.erb</p>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>

  <!-----------------------------------------! inizio parte centrale -->
    <section>
    
    <!------------------------------! inizio seconda parte -->
    	<div id="grafica"><div class="s_1260">
        	<h2>Trovare, proporre e realizzare:<br />
            il social network per i creativi<br />
            di tutto il mondo!</h2>
            <div class="clear"></div>
    	    <nav>
        		<ul id="pulsantoni">
            
            		<li><a href="#" class="p1">Farsi vedere</a></li>
            		<li><a href="#" class="p2">Ricercare</a></li>
            		<li><a href="#" class="p3">Collaborare</a></li>
                
           	    </ul>
      		</nav>
            <div class="clear"></div>
            <h3>Conosci Rainstorming design<br />
            e realizza la tua pioggia di idee!</h3>
        </div></div>
<!------------------------------! fine seconda parte -->

    
    	<div id="barra_menu2">
<!------------------------------! inizio menu2 -->
        	<h1 id="titoli_sezione">La pioggia del mese!</h1>
        	<nav>
            
            	<ul id="menu2">
                
                	<li><%= link_to "Designers", users_path, title: "I creative di Rainstorming Design" %></li>
                	<li><%= link_to "Progetti", progetti_path, title: "Progetti su Rainstorming Design" %></li>
                	<li><%= link_to "Annunci", annunci_path, title: "Annunci Rainstorming Design" %></li>
                
                </ul>
            
            </nav>
            <form id="search" method="get" action="#" ><input name="search" type="text" value="search"  /></form>
<!------------------------------! fine menu2 -->
        </div>
        
<!------------------------------! inizio parte elastica -->
<div id="elastico">
        
            <div class="col_lat">
            	<img scr="#" class="img_lat_1" />
               	<img scr="#" class="img_lat_2" />
            	<img scr="#" class="img_lat_1" />
            	<img scr="#" class="img_lat_2" />
            	<img scr="#" class="img_lat_1" />
            </div>
<!------------------------------! fine colonna laterale sx e inizio centrale -->
            <div class="col_cen">
            
            	<div class="cont_col_cent">
                	<div class="col_ccc_1">
                    	<img scr="#" class="img_cen_1"  style="margin-bottom:20px;"/>
                    	<img scr="#" class="img_cen_1" />
                    </div>
                    <div class="spazio_col_cent"></div>
                	<div class="col_ccc_2">
                    	<img scr="#" class="img_cen_2" />
                        <div class="annunci_cent"></div>
                    </div>
                </div>
                
                <div class="cont_col_cent">
                	<div class="col_ccc_2">
                    	<img scr="#" class="img_cen_2" />
                        <div class="annunci_cent"></div>
                    </div>
                    <div class="spazio_col_cent"></div>
                	<div class="col_ccc_1">
                    	<img scr="#" class="img_cen_1"  style="margin-bottom:20px;"/>
                    	<img scr="#" class="img_cen_1" />
                    </div>
                </div>

            	<div class="cont_col_cent">
                	<div class="col_ccc_1">
                    	<img scr="#" class="img_cen_1"  style="margin-bottom:20px;"/>
                    	<img scr="#" class="img_cen_1" />
                    </div>
                    <div class="spazio_col_cent"></div>
                	<div class="col_ccc_2">
                    	<img scr="#" class="img_cen_2" />
                        <div class="annunci_cent"></div>
                    </div>
                </div>
                
                <div class="cont_col_cent">
                	<div class="col_ccc_2">
                    	<img scr="#" class="img_cen_2" />
                        <div class="annunci_cent"></div>
                    </div>
                    <div class="spazio_col_cent"></div>
                	<div class="col_ccc_1">
                    	<img scr="#" class="img_cen_1"  style="margin-bottom:20px;"/>
                    	<img scr="#" class="img_cen_1" />
                    </div>
                </div>
            
            </div>
            <div class="col_cen" style="margin-left:20px;">
            
            	<div id="primo_annuncio"></div>
            
            	<div class="cont_col_cent">
                	<div class="col_ccc_1">
                    	<img scr="#" class="img_cen_1"  style="margin-bottom:20px;"/>
                    	<img scr="#" class="img_cen_1" />
                  </div>
                    <div class="spazio_col_cent"></div>
                	<div class="col_ccc_2">
                    	<img scr="#" class="img_cen_2" />
                        <div class="annunci_cent"></div>
                    </div>
              </div>
                
                <div class="cont_col_cent">
                	<div class="col_ccc_2">
                    	<img scr="#" class="img_cen_2" />
                        <div class="annunci_cent"></div>
                    </div>
                    <div class="spazio_col_cent"></div>
                	<div class="col_ccc_1">
                    	<img scr="#" class="img_cen_1"  style="margin-bottom:20px;"/>
                    	<img scr="#" class="img_cen_1" />
                    </div>
                </div>

            	<div class="cont_col_cent">
                	<div class="col_ccc_1">
                    	<img scr="#" class="img_cen_1"  style="margin-bottom:20px;"/>
                    	<img scr="#" class="img_cen_1" />
                    </div>
                    <div class="spazio_col_cent"></div>
                	<div class="col_ccc_2">
                    	<img scr="#" class="img_cen_2" />
                        <div class="annunci_cent"></div>
                    </div>
                </div>
                <div id="ultimo_annuncio"></div>
    </div>

<!------------------------------! fine colonna centrale e inizio dx -->
            <div class="col_lat">
            	<img scr="#" class="img_lat_1" />
               	<img scr="#" class="img_lat_2" />
            	<img scr="#" class="img_lat_1" />
            	<img scr="#" class="img_lat_2" />
            	<img scr="#" class="img_lat_1" />
            </div>

        </div>
<!------------------------------! fine parte elastica -->
    </section>
<!--------------------------------------------! fine parte centrale --><div class="clear"></div>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/sudinoi.html.erb
<h1>Pages#sudinoi</h1>
<p>Find me in app/views/pages/sudinoi.html.erb</p>

app/views/pages/termini.html.erb
<h1>Pages#termini</h1>
<p>Find me in app/views/pages/termini.html.erb</p>